//mongoose
const DB_PROVIDER = 'DatabaseProviders';
const USER_PROVIDER = 'UserProvider';
const RECOGNITION_PROVIDER = 'CompanyProvider';
export { DB_PROVIDER, USER_PROVIDER, RECOGNITION_PROVIDER };

//tokens
const ACCESS_TOKEN_TIMEOUT = '300s';
const REFRESH_TOKEN_TIMEOUT = '2400h';
const RESET_TOKEN_TIMEOUT = '1h';
export { ACCESS_TOKEN_TIMEOUT, REFRESH_TOKEN_TIMEOUT, RESET_TOKEN_TIMEOUT };
